name: Build Tweak Dylib

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Install Theos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
          
      - name: Build Dylib
        run: |
          export THEOS=~/theos
          make FINALPACKAGE=1
          
      - name: Upload Dylib
        uses: actions/upload-artifact@v4
        with:
          name: STS2_Mod_Loader_Dylib
          path: .theos/obj/**/*.dylib
